### ISSUE TITLE
Clarify / make more uniform handling for templates without logic

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/template-archive#597]
**Is your feature request related to a problem? Please describe.**
Currently:
- templates without logic or formulas support `parse` and `draft` but no other command (e.g., `initialize` or `trigger`)
- templates with logic support all commands
- templates without logic but with formulas are handled like contracts with logic

This can be a bit surprising, especially `cicero initialize` sometimes works when there is no logic (e.g., when a formula is in the template grammar).

Also this means testing logicless templates is somewhat cumbersome / different from other templates.

This can also mean some API calls will throw lower-level exceptions for logicless templates in some cases.

**Describe the solution you'd like**
More uniform handling of templates with or without logic. For instance:
- Contracts without logic are treated as having empty contract logic (i.e., a contract with a single default `initialize` clause)

**Additional context**
Example with the signature block template from https://templates.accordproject.org/signature-block-title-name-date@0.19.0.html

```
bash-3.2$ cicero --version
0.21.9
bash-3.2$ cicero parse 
2:49:18 PM - info: Using current directory as template folder
2:49:18 PM - info: Loading a default text/sample.md file.
2:49:19 PM - info:
{
  "$class": "org.accordproject.signature.tnd.TitleNameDateSignatureBlock",
  "title": "Title",
  "signature": "--------",
  "fullName": "Full Name",
  "dateSigned": "Date Signed",
  "signatory": "resource:org.accordproject.cicero.contract.AccordParty#buyer@example.com",
  "clauseId": "ddb2dcef-97ba-4aa4-ab70-7cc1002d0a52"
}
bash-3.2$ cicero initialize 
2:49:22 PM - info: Using current directory as template folder
2:49:22 PM - info: Loading a default text/sample.md file.
2:49:23 PM - error: Did not find any compiled JavaScript logic
```

**Comment by jeromesimeon** [comment]
^^^ @dselman

**Comment by jeromesimeon** [comment]
Note, this also mean that logicless templates, currently, cannot be open in template studio:

<img width="1130" alt="Screenshot 2020-10-07 at 3 07 41 PM" src="https://user-images.githubusercontent.com/670099/95376320-eee13380-08ae-11eb-9873-2da00ddaef86.png">

<img width="1364" alt="Screenshot 2020-10-07 at 3 07 18 PM" src="https://user-images.githubusercontent.com/670099/95376331-f1438d80-08ae-11eb-806c-159a3d76606f.png">

**Comment by sanketshevkar** [comment]
@jeromesimeon while investigating this issue, I was working with ergo-engine code. I found out the following behaviour.

- While I was using ergo-engine v0.21.9 I was able to use init method and it gave a output as expected. I initialised the [helloworldstate](https://templates.accordproject.org/helloworldstate@0.14.0.html) template.
- But then I linked the ergo-engine v0.22.0 alpha.4 that time using init method gave out this error. 

```
(node:29066) UnhandledPromiseRejectionWarning: TypeNotFoundException: Namespace is not defined for type org.accordproject.runtime.State
    at APModelManager.getType (/home/user/Desktop/templateHandling/node_modules/@accordproject/concerto-core/lib/modelmanager.js:569:19)
    at Serializer.fromJSON (/home/user/Desktop/templateHandling/node_modules/@accordproject/concerto-core/lib/serializer.js:149:52)
    at LogicManager.validateInput (/home/user/Desktop/templateHandling/node_modules/@accordproject/ergo-compiler/lib/logicmanager.js:324:39)
    at VMEngine.invoke (/home/user/Documents/ergo/packages/ergo-engine/lib/engine.js:170:34)
    at VMEngine.init (/home/user/Documents/ergo/packages/ergo-engine/lib/engine.js:215:21)
    at Engine.init (/home/user/Desktop/templateHandling/node_modules/@accordproject/cicero-engine/lib/engine.js:85:32)
    at main (/home/user/Desktop/templateHandling/index.js:20:30)
```

.

I guess v0.22.0 still must be in development so just thought of reporting this behaviour to you.

**Comment by sanketshevkar** [comment]
Hello @jeromesimeon ,
I wanted to test a template with formulae but without logic. Can you please suggest a template that I can use for the same?

**Comment by jeromesimeon** [comment]
> I guess v0.22.0 still must be in development so just thought of reporting this behaviour to you.

It's expected. Not really because Ergo `0.22` is still an alpha version (although, of course it is), but simply because that new version is a breaking change so we have to make changes to template studio to support it.

**Comment by jeromesimeon** [comment]
> Hello @jeromesimeon ,
> I wanted to test a template with formulae but without logic. Can you please suggest a template that I can use for the same?

Look in the template library for templates without a logic directory (I think there are a few).

**Comment by jeromesimeon** [comment]
> > Hello @jeromesimeon ,
> > I wanted to test a template with formulae but without logic. Can you please suggest a template that I can use for the same?
> 
> Look in the template library for templates without a logic directory (I think there are a few).

@sanketshevkar I think I read your question a little fast. I don't think there is one without logic but with formulae... Someone will have to try and create one!

**Comment by sanketshevkar** [comment]
@jeromesimeon I have searched templates in cicero template library, but found none.

Also, I was curious that what would be the cases where there could be a need to `initialize` and `trigger` templates without logic? Since no logic involved, there is no state type, request type, response type and emit type associated with it. 

If we want to `initialize` these templates we'll need at least need a state type and a response type associated with it. Is that correct?

**Comment by jeromesimeon** [comment]
> @jeromesimeon I have searched templates in cicero template library, but found none.
> 
> Also, I was curious that what would be the cases where there could be a need to `initialize` and `trigger` templates without logic? Since no logic involved, there is no state type, request type, response type and emit type associated with it.
> 
> If we want to `initialize` these templates we'll need at least need a state type and a response type associated with it. Is that correct?

Those are all good question. I think it depends how you think of "no logic" is it really no logic, or is it "empty logic" in which case you could have a default initialisation to an empty state and no request would trigger execution but the trigger call could still exist.

**Comment by sanketshevkar** [comment]
Thank you @jeromesimeon. I think this problem is better handle from the ergo packages than cicero. I am trying the same. Would that be correct thing to do?

Also, do all templates need to have a contractName? I am the same signature block template you used above. I'm getting a error in ergo-engine because the contractName is null.

**Comment by jeromesimeon** [comment]
@sanketshevkar I think it could probably be handled directly in template studio? This would be worth investigating as it's much less intrusive. (i.e., not do the invoke call in the first place)

**Comment by sanketshevkar** [comment]
@jeromesimeon, yeah I'll investigate this approach too. But then `cicero init` & `cicero trigger` would still fail.

I have changed some code on the `ergo-engine` and `ergo-compiler` v0.21.9 to solve this issue. Should I create a PR for that?

**Comment by jeromesimeon** [comment]
> @jeromesimeon, yeah I'll investigate this approach too. But then `cicero init` & `cicero trigger` would still fail.
> 
> I have changed some code on the `ergo-engine` and `ergo-compiler` v0.21.9 to solve this issue. Should I create a PR for that?

Right. yes sorry I confused two different issues here maybe. sure, if you have something to review, I'll be happy to take a look.

**Comment by sanketshevkar** [comment]
> > @jeromesimeon, yeah I'll investigate this approach too. But then `cicero init` & `cicero trigger` would still fail.
> > I have changed some code on the `ergo-engine` and `ergo-compiler` v0.21.9 to solve this issue. Should I create a PR for that?
> 
> Right. yes sorry I confused two different issues here maybe. If we do want to support `initialise` even in the absence of user-logic, it's quite possible that doing it in Ergo as you suggest would be better. And sure, if you have something to review, I'll be happy to take a look!

Hi @jeromesimeon,

I have created a PR for the ergo respository.
